version: '2'

services:

  nifi:
    image: "aldrin/apache-nifi"
    ports:
      - "8443:443"
      - "8444:80"
    environment:
     DISABLE_SSL: "true"
  
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.3.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      #ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # disable X-Pack security
      # see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
      #     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.watcher.enabled: "false"
      xpack.graph.enabled: "true"
    networks:
      - elk

  kibana:
    build: "docker.elastic.co/kibana/kibana:5.3.0"
    #volumes:
    #  - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge